---
applications:
- name: ct_reports2_api
  memory: 2G
  buildpack: nodejs_buildpack
  path: ../../../server/
  services:
    - ct_reports
- name: ct_reports2_app
  memory: 1G
  buildpack: staticfile_buildpack
  path: ../../../dist/tep-test-report/
